### ISSUE TITLE
AsksinPP-Projekt-Galerie

### ISSUE THREAD

**Issue by christoph-morrison** [paso42/HM-Bell#1]
Wäre toll wenn du das Projekt in die AsksinPP-Projektgalerie [aufnimmst](https://asksinpp.de/Projekte/Projekt-hinzufuegen.html)

**Comment by paso42** [comment]
Hallo, ich hatte Psi schon mal darauf angesprochen, bisher wurde es jedoch noch nicht aufgenommen. Da ich mich selbst bisher auch nicht mehr mit Git auseinander gesetzt habe als für dieses Projekt, wäre ich für jede Hilfe dankbar. Nach meinem letzten Stand sollte alles für die Asksinpp Projektgalerie vorhanden sein, allerdings scheint es so, als hätte sich seit meinem letzten Login hier auch die Markdown Struktur geändert. Ich erstelle mal ein Issue zur Aufnahme. Falls da noch was fehlt, sollte ich ja auch darüber bescheid bekommen. Viele Grüße und danke für die Anregung

**Comment by paso42** [comment]
Ist drin

**Comment by christoph-morrison** [comment]
Super!
